- name: Copy DB script
  become: yes
  template:
    src: "data.cql.j2"
    dest: "{{ analytics_user_home }}/data.cql"
    mode: 0644

- name: run cql
  raw: /bin/bash -c 'CQLSH_NO_BUNDLED=true {{cql_path}} -f {{analytics_user_home}}/data.cql'
  ignore_errors: yes
