- hosts: "{{ remote }}"
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets/dp_secrets.yml', '{{inventory_dir}}/secrets/lp_secrets.yml']
  roles:
    - es-azure-snapshot
  tags:
    - es_backup