---
- hosts: spark
  vars_files:
    - "{{inventory_dir}}/secrets/dp_secrets.yml"
  roles:
    - analytics-bootstrap-always
    - analytics-bootstrap-spark 
    - at-ruby
    - analytics-spark-provision
    
