---
- hosts: analytics-api
  vars_files:
    - "{{inventory_dir}}/secrets/dp_secrets.yml"
  become: yes
  gather_facts: false
  roles:
   - analytics-bootstrap-always       
   - analytics-api-provision
