- hosts: kafka-indexer
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  name: Installing and configuring monit
  roles:
    - { role: monit, service: 'monit_logstash_ep' }
  tags: kafka-indexer


- hosts: analytics-api
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  name: Installing and configuring monit
  roles:
    - { role: monit, service: 'monit_api-service' }
  tags: analytics-api

- hosts: cassandra
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  name: Installing and configuring monit
  roles:
    - { role: monit, service: 'monit_cassandra-dp' }
  tags: cassandra

- hosts: influxdb
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  name: Installing and configuring monit
  roles:
    - { role: monit, service: 'monit_influxdb' }
  tags: influxdb

- hosts: telemetry-search-cluster-kibana-node
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  name: Installing and configuring monit
  roles:
    - { role: monit, service: 'monit_kibana' }
  tags: kibana

- hosts: secor
  become: yes
  vars_files:
    - ['{{inventory_dir}}/secrets.yml']
  name: Installing and configuring monit
  roles:
    - { role: monit, service: 'monit_channel-telemetry-backup,monit_derived-telemetry-backup,monit_raw-telemetry-backup,monit_learning-events-backup,monit_ingestion-telemetry-backup,monit_unique-telemetry-backup,monit_failed-telemetry-backup' }
  tags: secor

